//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 11:29:01 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.thalesgroup.com/rtti/XmlTimetable/v8", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.artronics.rail.darwin.pport.v12;
