//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 11:29:00 PM GMT 
//


package com.artronics.rail.darwin.pport.v12;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * An update to a Darwin alarm.
 * 
 * <p>Java class for RTTIAlarm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTTIAlarm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="set" type="{http://www.thalesgroup.com/rtti/PushPort/Alarms/v1}RTTIAlarmData"/>
 *         &lt;element name="clear" type="{http://www.thalesgroup.com/rtti/PushPort/Alarms/v1}AlarmID"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTTIAlarm", namespace = "http://www.thalesgroup.com/rtti/PushPort/Alarms/v1", propOrder = {
    "set",
    "clear"
})
public class RTTIAlarm {

    protected RTTIAlarmData set;
    protected String clear;

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link RTTIAlarmData }
     *     
     */
    public RTTIAlarmData getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTTIAlarmData }
     *     
     */
    public void setSet(RTTIAlarmData value) {
        this.set = value;
    }

    /**
     * Gets the value of the clear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClear() {
        return clear;
    }

    /**
     * Sets the value of the clear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClear(String value) {
        this.clear = value;
    }

}
